service: PDPlatformEngineerProject

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SNSTopicARN: "${self:resources.Outputs.SNSTopicArn.Value}"
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "sns:Publish"
         - "sns:Subscribe"
         - "sns:Unsubscribe"
         - "sns:ListSubscriptionsByTopic"
       Resource:
         - "${self:resources.Outputs.SNSTopicArn.Value}"

functions:
  sendDailyDadJoke:
    handler: send_notification.sendDailyDadJoke
    events:
      # Invoke the Lambda function everyday
      - schedule: rate(1 day)
  subscribe:
    handler: subscribe.subscribe
    events:
      - http:
          path: api/subscribe
          method: post
          integration: lambda
          cors: true  
  unsubscribe:
    handler: unsubscribe.unsubscribe
    events:
      - http:
          path: api/unsubscribe
          method: post
          integration: lambda
          cors: true  
resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      
  Outputs:
    SNSTopicArn:
      Value:
        Ref: SNSTopic
